#!/bin/sh

ToolPath='/usr/local/bin'

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

if [ -e "/dev/i2c-5" ]; then
   BUS=5
else
   echo "I2C bus (i2c-5) not found."
   exit 1
fi

modprobe at24
rc=$?
if [ "$rc" != 0 ]; then
   echo "Modprobe of at24 failed."
   exit $rc
fi

SYS=/sys/class/i2c-adapter/i2c-$BUS

rm -f /etc/mcc/hats/*.bin

echo "Reading..."

index=0
while [ "$index" -lt 8 ]
do
   address=$((0x50 + $index))
   devname=$(printf '%s/%s-%04x' $SYS $BUS $address)
   if [ ! -d "$devname" ]; then
      printf '24c32 0x%x' $address > $SYS/new_device
   fi

   # try to read the eeprom
   dd if=$devname/eeprom of=/dev/null bs=1 count=1 status=none 2> /dev/null
   rc=$?

   if [ "$rc" -eq 0 ]; then
      # successs, read the entire eeprom
      printf "Found EEPROM at address %d\n" $index
      if [ "$index" != "0" ]; then
         if [ ! -e "/etc/mcc/hats" ]; then
            mkdir -p "/etc/mcc/hats"
         fi
         dd if=$devname/eeprom of=/etc/mcc/hats/eeprom_$index.bin status=none
         sync
      fi
   fi

   # remove the device
   printf '0x%x' $address > $SYS/delete_device

   index=$(($index + 1))
done

modprobe -r at24

echo "Done"
